services:
  db:
    image: postgres:16
    container_name: wingz-db
    environment:
      POSTGRES_DB: wingz
      POSTGRES_USER: wingz
      POSTGRES_PASSWORD: wingz
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wingz -d wingz"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata:
