# Generated by Django 6.1 on 2026-08-19 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Field order inside CreateModel is deliberate: it mirrors the
    # assessment's table definitions. makemigrations appends foreign keys
    # to the end and sorts them alphabetically, which would have produced
    # a physical column order that does not match the spec.
    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id_ride', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('en-route', 'En route'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=20)),
                ('id_rider', models.ForeignKey(db_column='id_rider', on_delete=django.db.models.deletion.PROTECT, related_name='rides_as_rider', to=settings.AUTH_USER_MODEL)),
                ('id_driver', models.ForeignKey(db_column='id_driver', on_delete=django.db.models.deletion.PROTECT, related_name='rides_as_driver', to=settings.AUTH_USER_MODEL)),
                ('pickup_latitude', models.FloatField()),
                ('pickup_longitude', models.FloatField()),
                ('dropoff_latitude', models.FloatField()),
                ('dropoff_longitude', models.FloatField()),
                ('pickup_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'ride',
                'ordering': ['id_ride'],
            },
        ),
        migrations.CreateModel(
            name='RideEvent',
            fields=[
                ('id_ride_event', models.AutoField(primary_key=True, serialize=False)),
                ('id_ride', models.ForeignKey(db_column='id_ride', db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='rides.ride')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ride_event',
                'ordering': ['id_ride_event'],
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['pickup_time'], name='ride_pickup_time_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status'], name='ride_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.CheckConstraint(condition=models.Q(('pickup_latitude__gte', -90), ('pickup_latitude__lte', 90)), name='ride_pickup_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.CheckConstraint(condition=models.Q(('pickup_longitude__gte', -180), ('pickup_longitude__lte', 180)), name='ride_pickup_longitude_range'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.CheckConstraint(condition=models.Q(('dropoff_latitude__gte', -90), ('dropoff_latitude__lte', 90)), name='ride_dropoff_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='ride',
            constraint=models.CheckConstraint(condition=models.Q(('dropoff_longitude__gte', -180), ('dropoff_longitude__lte', 180)), name='ride_dropoff_longitude_range'),
        ),
        migrations.AddIndex(
            model_name='rideevent',
            index=models.Index(fields=['id_ride', 'created_at'], name='ride_event_ride_time_idx'),
        ),
    ]
