# Generated by Django 6.1 on 2026-08-20 03:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ride',
            name='ride_pickup_time_idx',
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['pickup_time', 'id_ride'], name='ride_pickup_time_id_idx'),
        ),
    ]
